### ISSUE TITLE
Startup redraws everything

### ISSUE THREAD

**Issue by noahbald** [notomo/zebrazone.nvim#4]
Right now the highlighter startup uses `vim.cmd("redraw!")` which redraws everything. We could instead use `vim.api.nvim__redraw({ buf: bufnr, valid: true })` to redraw only the buffer.

For me, this brings the startup time from 3.87ms to 0.03ms

**Comment by notomo** [comment]
Thanks!

notomo/zebrazone.nvim@5d436cb
